version: '3'

services:
#Database
  db:
    image: mysql:8.0
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped
    container_name: db
    env_file: .env
    environment: 
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_HOST: '%'
    networks:
      - wordpress
    command: --default-authentication-plugin=mysql_native_password
  #phpmyadmin
  phpmyadmin:  
    depends_on: 
      - db
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    container_name: phpmyadmin
    ports: 
      - '8080:80'
    env_file: .env
    environment: 
      PMA_HOST: db
    networks: 
      - wordpress
  #Wordpress
  wordpress:
    depends_on: 
      - db
    image: wordpress:fpm-alpine
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
    container_name: wordpress
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    networks: 
      - wordpress
  #Nginx webserver
  webserver:
    depends_on:
      - wordpress
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - wordpress
  #SSL Certification
  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email ${EMAIL} --agree-tos --no-eff-email --force-renewal -d  ${DOMAIN_NAME} -d www.${DOMAIN_NAME}
networks: 
  wordpress:
    driver: bridge
volumes: 
  certbot-etc:
  wordpress:
  dbdata:
